### PR TITLE
ENH: TDC releated changes

### PR DESCRIPTION
**Pull request by laborleben**
Hi,
I have some TDC related changes.
David, can you review the code?
1. added a new case where _alignAtTriggerNumber AND _useTdcTriggerDistance are true
   
   Here we have the case that the very first TDC immediately after the trigger word and before the first data header should count. If there are more than 1 TDC words immediately after the trigger, set appropriate event error code. Ignore all other TDC if they come after the first data header (these are very late TDC words anyway).
2. The remaining code should still do the same, but I carefully check for TDC errors (e.g. TDC value != 0, TDC distance != 255).

### CODE REVIEW

**Comment by DavidLP** [comment]
1. is only needed if the trigger number comes not always first? Otherwise the wanted behavior (take first TDC word and align at trigger number, set error code accordingly) should be already there?

**Comment by laborleben** [comment]
Yeah, but how it was before, the event error code __MANY_TDC_WORDS would be set if another valid TDC word (TDC distance != 255) would appear (even after the first data header). Now it is only marked as __MANY_TDC_WORDS when another TDC word appears before the first data header.
The TDC distance can only measure delays of (255-1) \* 1.5625ns which is nothing compared to the time needed to send out the first data header. So I expect the TDC word after the trigger word and before the first data header.
The length of the TDC cable should be carefully chosen so that the TDC trigger signal arrives before the TDC signal. But this is anyway necessary for the TDC distance measurement.
I will also add the TDC distance histogram to this pull request so that we can integrate the TDC distance histogram into the online monitor.

**Comment by laborleben** [comment]
I still don't know what you mean.

I inserted tabs everywhere I could find spaces or a mixture of both. The tab stop can be set up in your editor.

**Comment by DavidLP** [comment]
> Now it is only marked as __MANY_TDC_WORDS when another TDC word appears before the first data header.

I think every event with more than one TDC word should have the flag __MANY_TDC_WORDS set. You cannot assign the hit info to the TDC info for that event. The FE hit words do not arrive sorted in time!

**Comment by DavidLP** [comment]
This is complex code. I cannot merge if there are no unit tests proving that the result is correct.

**Comment by laborleben** [comment]
Won't merge.

**Pull request closed without merging**
