### PR TITLE
Trigger data format support

### PR DESCRIPTION
**Pull request by laborleben**
This is adding trigger data format support to the FEI4 interpreter.

Old and deprecated code was removed (e.g. useTriggerTimeStamp(), ...).

### CODE REVIEW

**Comment by laborleben** [comment]
Yannick, can you give feedback for the comment above?

**Comment by laborleben** [comment]
I saw that you changed the pyBAR code to include the data format feature, but there is no release for the FEI4 interpreter available that has this feature included. This situation is unfortunate, since the pyBAR development is broken.

I think we should hurry up and finish this branch.

**Comment by YannickDieter** [comment]
Ah okay, yes thats true. I though that we would merge the trigger_data_format branch in the development branch.

Is there any reason to not do this?

**Comment by laborleben** [comment]
I'm working on that right now. There is another feature that needs to be implemented. Please wait for the commit. Can you fix the unit test, just add several events each having a trigger data word (not just one at the very beginning).

**Comment by YannickDieter** [comment]
Okay. Yes of course!

**Pull request merged**
